# PostgreSQL. Versions 9.3 and up are supported.
#
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: post_metrics_development
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

test:
  <<: *default
  database: post_metrics_test

production:
  primary: &primary_production
    <<: *default
    database: post_metrics_production
    username: post_metrics
    password: <%= ENV["POST_METRICS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: post_metrics_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: post_metrics_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: post_metrics_production_cable
    migrations_paths: db/cable_migrate
